### ISSUE TITLE
Should use `prometheus_scrape` lib facilities for constructing relation data

### ISSUE THREAD

**Issue by sed-i** [canonical/prometheus-scrape-target-k8s-operator#20]
### Enhancement Proposal

Currently, the charm generates relation data for the `prometheus_scrape` integration on its own:

https://github.com/canonical/prometheus-scrape-target-k8s-operator/blob/85c96672559ac5d18f0f0b36c23a0b75f4400fbc/src/charm.py#L74-L76

It could be handy if the charm could use `prometheus_scrape` lib facilities for constructing relation data.

Related to https://github.com/canonical/prometheus-k8s-operator/pull/340 (merging AlertRules provider).

**Comment by simskij** [comment]
This charm is simple enough for that not to be needed. The current implementation is quite smooth to work with as-is.
