### ISSUE TITLE
Surface `params` as charm config

### ISSUE THREAD

**Issue by simskij** [canonical/prometheus-scrape-target-k8s-operator#26]
### Enhancement Proposal

To support using scrape-target with federated endpoints, we need to surface the `params` part of the scrape job to allow for setting federation matches.

**Comment by lucabello** [comment]
The `params` configuration parameters is in `scrape_config` as shown [here](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config).

**Comment by peppepetra** [comment]
We need that to use scrape config with `/federate` which requires match.

https://prometheus.io/docs/prometheus/latest/federation/
